name: TRMNL Terminus
version: 0.2.0-dev3
slug: trmnl_terminus
description: >
  A self-hosted TRMNL Terminus server for Home Assistant.
arch:
  - aarch64
  - amd64
url: https://github.com/lzulauf/hassio-addon-trmnl-terminus
image: ghcr.io/lzulauf/hassio-trmnl-terminus
startup: services
init: false
boot: auto
ingress: true
ingress_port: 2300
ingress_stream: true
ports:
  2300/tcp: 2300
ports_description:
  2300/tcp: Terminus web and API port
map:
  - addon_config:rw
stage: experimental
options:
  api_uri: "http://homeassistant.local:2300"
  app_secret: ""
  app_setup: true
  certificate_urls: ""
schema:
  api_uri: str
  app_secret: password?
  app_setup: bool
  certificate_urls: str?
